services:
  airflow:
    build:
      context: .
      dockerfile: docker/airflow/Dockerfile
    container_name: healthcare-airflow
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__EXECUTOR: "SequentialExecutor"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "sqlite:////opt/airflow/airflow.db"
      AIRFLOW__CORE__DAGS_FOLDER: "/opt/airflow/dags"
      AIRFLOW_HOME: "/opt/airflow"
      PYTHONPATH: "/opt/airflow/repo"
      DBT_PROFILES_DIR: "/opt/airflow/dbt_profiles"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./:/opt/airflow/repo
      - ./docker/dbt_profiles:/opt/airflow/dbt_profiles
    working_dir: /opt/airflow/repo
    command: >
      bash -c "
        airflow db migrate &&
        airflow users list | grep -q ${AIRFLOW_ADMIN_USERNAME} || airflow users create \
          --username ${AIRFLOW_ADMIN_USERNAME} \
          --firstname ${AIRFLOW_ADMIN_FIRSTNAME} \
          --lastname ${AIRFLOW_ADMIN_LASTNAME} \
          --role Admin \
          --email ${AIRFLOW_ADMIN_EMAIL} \
          --password ${AIRFLOW_ADMIN_PASSWORD} &&
        airflow standalone
        "